### PR TITLE
Fix offset

### LINKED ISSUE #43: Leading backslash causes wrong pos.Offset
I want to extract `:function` ~ `:endfunction` block from source.
But parsing the following script causes wrong `endpos.Offset`.

## Vim script

```vim
function! s:load_on()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfunction
```

## Parser

```go
func main() {
	src := `
function! s:load_on()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfunction
`

	file, err := vimlparser.ParseFile(strings.NewReader(src), "src.vim", nil)
	if err != nil {
		panic(err)
	}

	// Inspect nodes and get above values from plugconf script
	ast.Inspect(file, func(node ast.Node) bool {
		// Cast to function node (return if it's not a function node)
		var fn *ast.Function
		if f, ok := node.(*ast.Function); !ok {
			return true
		} else {
			fn = f
		}

		body := extractBody(fn, src)
		fmt.Printf("[%s]\n", body)

		return true
	})

}

func extractBody(fn *ast.Function, src string) string {
	pos := fn.Pos()

	// TODO: Handle line break
	endpos := fn.EndFunction.Pos()
	endfunc := fn.EndFunction.ExArg
	cmdlen := endfunc.Argpos.Offset - endfunc.Cmdpos.Offset
	endpos.Offset += cmdlen

	return src[pos.Offset:endpos.Offset]
}
```

## Output

`:endfunction` is truncated to `endfuncti`.

```
function! s:load_on()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfuncti
```

## Whole source code

https://gist.github.com/tyru/dd804f78add8c4e01fd02a13950d083a

### PR DESCRIPTION
**Pull request by haya14busa**
Fix #43 

vim-vimlparser side change: https://github.com/vim-jp/vim-vimlparser/pull/69

### CODE REVIEW

File: go/type.go [hunk 1]
```diff
@@ -214,15 +218,18 @@ func (self *StringReader) __init__(lines []string) {
 					self.pos = append(self.pos, pos{lnum: lnum + 2, col: col + 1})
 				}
 				col += len(c)
+				offset += len(c)
 			}
 			lnum += 1
+			offset += 1
```
Comment (haya14busa) [inline go/type.go]: **[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
should replace offset += 1 with offset++

File: go/type.go [hunk 2]
```diff
@@ -214,15 +218,18 @@ func (self *StringReader) __init__(lines []string) {
...
 		}
 		self.buf = append(self.buf, "<EOL>")
-		self.pos = append(self.pos, pos{lnum: lnum + 1, col: col + 1})
+		self.pos = append(self.pos, pos{lnum: lnum + 1, col: col + 1, offset: offset})
 		lnum += 1
+		offset += 1
```
Comment (haya14busa) [inline go/type.go]: **[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
should replace offset += 1 with offset++

File: go/type.go [hunk 3]
```diff
@@ -173,9 +174,10 @@ func NewLvalueParser(reader *StringReader) *LvalueParser {
 }
 
 type StringReader struct {
-	i   int
-	pos []pos
-	buf []string
+	i      int
+	pos    []pos
+	buf    []string
+	offset []int
```
Comment (haya14busa) [inline go/type.go]: <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
field offset is unused (U1000)
